sudo: required

language: ruby

services:
  - docker

env:
  - PUPPET_VERSION=4.10
  - PUPPET_VERSION=5.3
  - PUPPET_VERSION=5.5
  - PUPPET_VERSION=6.0

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

matrix:
  include:
    - name: Puppet 4.10
      env: PUPPET_VERSION=4.10
    - name: Puppet 5.3
      env: PUPPET_VERSION=5.3
    - name: Puppet 5.5
      env: PUPPET_VERSION=5.5
    - name: Puppet 6.0
      env: PUPPET_VERSION=6.0
  script:
    - 'make puppet_${PUPPET_VERSION}'
    - 'make push_puppet_${PUPPET_VERSION}'
