source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem 'rake',                                                       :require => false
gem 'rspec-puppet',                                               :require => false, :git => 'https://github.com/rodjek/rspec-puppet.git'
gem 'puppet-lint',                                                :require => false, :git => 'https://github.com/rodjek/puppet-lint.git'
gem 'metadata-json-lint',                                         :require => false
gem 'rspec-puppet-facts',                                         :require => false
gem 'rspec',                                                      :require => false
gem 'rspec-puppet-utils',                                         :require => false
gem 'puppetlabs_spec_helper',                                     :require => false

if facterversion = ENV['FACTER_VERSION']
  gem 'facter', facterversion.to_s, :require => false, :groups => [:test]
else
  gem 'facter', :require => false, :groups => [:test]
end

ENV['PUPPET_VERSION'].nil? ? puppetversion = '~> 3.8' : puppetversion = ENV['PUPPET_VERSION'].to_s
gem 'puppet', puppetversion, :require => false, :groups => [:test]
